/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WomenRouteImport } from './routes/women'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as SnapshotRouteImport } from './routes/snapshot'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NewArrivalsRouteImport } from './routes/new-arrivals'
import { Route as MenRouteImport } from './routes/men'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KidsRouteImport } from './routes/kids'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as ProfileWishlistRouteImport } from './routes/profile/wishlist'
import { Route as ProfilePaymentRouteImport } from './routes/profile/payment'
import { Route as ProfilePasswordRouteImport } from './routes/profile/password'
import { Route as ProfileOrdersRouteImport } from './routes/profile/orders'
import { Route as ProfileEditRouteImport } from './routes/profile/edit'
import { Route as ProfileAddressesRouteImport } from './routes/profile/addresses'
import { Route as ProductIdRouteImport } from './routes/product.$id'

const WomenRoute = WomenRouteImport.update({
  id: '/women',
  path: '/women',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SnapshotRoute = SnapshotRouteImport.update({
  id: '/snapshot',
  path: '/snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NewArrivalsRoute = NewArrivalsRouteImport.update({
  id: '/new-arrivals',
  path: '/new-arrivals',
  getParentRoute: () => rootRouteImport,
} as any)
const MenRoute = MenRouteImport.update({
  id: '/men',
  path: '/men',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsRoute = KidsRouteImport.update({
  id: '/kids',
  path: '/kids',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileWishlistRoute = ProfileWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfilePaymentRoute = ProfilePaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfilePasswordRoute = ProfilePasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileOrdersRoute = ProfileOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileAddressesRoute = ProfileAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => ProfileRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/kids': typeof KidsRoute
  '/login': typeof LoginRoute
  '/men': typeof MenRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/profile': typeof ProfileRouteWithChildren
  '/signup': typeof SignupRoute
  '/snapshot': typeof SnapshotRoute
  '/wishlist': typeof WishlistRoute
  '/women': typeof WomenRoute
  '/product/$id': typeof ProductIdRoute
  '/profile/addresses': typeof ProfileAddressesRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/orders': typeof ProfileOrdersRoute
  '/profile/password': typeof ProfilePasswordRoute
  '/profile/payment': typeof ProfilePaymentRoute
  '/profile/wishlist': typeof ProfileWishlistRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/kids': typeof KidsRoute
  '/login': typeof LoginRoute
  '/men': typeof MenRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/signup': typeof SignupRoute
  '/snapshot': typeof SnapshotRoute
  '/wishlist': typeof WishlistRoute
  '/women': typeof WomenRoute
  '/product/$id': typeof ProductIdRoute
  '/profile/addresses': typeof ProfileAddressesRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/orders': typeof ProfileOrdersRoute
  '/profile/password': typeof ProfilePasswordRoute
  '/profile/payment': typeof ProfilePaymentRoute
  '/profile/wishlist': typeof ProfileWishlistRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/kids': typeof KidsRoute
  '/login': typeof LoginRoute
  '/men': typeof MenRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/profile': typeof ProfileRouteWithChildren
  '/signup': typeof SignupRoute
  '/snapshot': typeof SnapshotRoute
  '/wishlist': typeof WishlistRoute
  '/women': typeof WomenRoute
  '/product/$id': typeof ProductIdRoute
  '/profile/addresses': typeof ProfileAddressesRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/orders': typeof ProfileOrdersRoute
  '/profile/password': typeof ProfilePasswordRoute
  '/profile/payment': typeof ProfilePaymentRoute
  '/profile/wishlist': typeof ProfileWishlistRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/forgot-password'
    | '/kids'
    | '/login'
    | '/men'
    | '/new-arrivals'
    | '/profile'
    | '/signup'
    | '/snapshot'
    | '/wishlist'
    | '/women'
    | '/product/$id'
    | '/profile/addresses'
    | '/profile/edit'
    | '/profile/orders'
    | '/profile/password'
    | '/profile/payment'
    | '/profile/wishlist'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/forgot-password'
    | '/kids'
    | '/login'
    | '/men'
    | '/new-arrivals'
    | '/signup'
    | '/snapshot'
    | '/wishlist'
    | '/women'
    | '/product/$id'
    | '/profile/addresses'
    | '/profile/edit'
    | '/profile/orders'
    | '/profile/password'
    | '/profile/payment'
    | '/profile/wishlist'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/forgot-password'
    | '/kids'
    | '/login'
    | '/men'
    | '/new-arrivals'
    | '/profile'
    | '/signup'
    | '/snapshot'
    | '/wishlist'
    | '/women'
    | '/product/$id'
    | '/profile/addresses'
    | '/profile/edit'
    | '/profile/orders'
    | '/profile/password'
    | '/profile/payment'
    | '/profile/wishlist'
    | '/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  KidsRoute: typeof KidsRoute
  LoginRoute: typeof LoginRoute
  MenRoute: typeof MenRoute
  NewArrivalsRoute: typeof NewArrivalsRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  SignupRoute: typeof SignupRoute
  SnapshotRoute: typeof SnapshotRoute
  WishlistRoute: typeof WishlistRoute
  WomenRoute: typeof WomenRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/women': {
      id: '/women'
      path: '/women'
      fullPath: '/women'
      preLoaderRoute: typeof WomenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snapshot': {
      id: '/snapshot'
      path: '/snapshot'
      fullPath: '/snapshot'
      preLoaderRoute: typeof SnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-arrivals': {
      id: '/new-arrivals'
      path: '/new-arrivals'
      fullPath: '/new-arrivals'
      preLoaderRoute: typeof NewArrivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/men': {
      id: '/men'
      path: '/men'
      fullPath: '/men'
      preLoaderRoute: typeof MenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids': {
      id: '/kids'
      path: '/kids'
      fullPath: '/kids'
      preLoaderRoute: typeof KidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/wishlist': {
      id: '/profile/wishlist'
      path: '/wishlist'
      fullPath: '/profile/wishlist'
      preLoaderRoute: typeof ProfileWishlistRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/payment': {
      id: '/profile/payment'
      path: '/payment'
      fullPath: '/profile/payment'
      preLoaderRoute: typeof ProfilePaymentRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/password': {
      id: '/profile/password'
      path: '/password'
      fullPath: '/profile/password'
      preLoaderRoute: typeof ProfilePasswordRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/orders': {
      id: '/profile/orders'
      path: '/orders'
      fullPath: '/profile/orders'
      preLoaderRoute: typeof ProfileOrdersRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/addresses': {
      id: '/profile/addresses'
      path: '/addresses'
      fullPath: '/profile/addresses'
      preLoaderRoute: typeof ProfileAddressesRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProfileRouteChildren {
  ProfileAddressesRoute: typeof ProfileAddressesRoute
  ProfileEditRoute: typeof ProfileEditRoute
  ProfileOrdersRoute: typeof ProfileOrdersRoute
  ProfilePasswordRoute: typeof ProfilePasswordRoute
  ProfilePaymentRoute: typeof ProfilePaymentRoute
  ProfileWishlistRoute: typeof ProfileWishlistRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileAddressesRoute: ProfileAddressesRoute,
  ProfileEditRoute: ProfileEditRoute,
  ProfileOrdersRoute: ProfileOrdersRoute,
  ProfilePasswordRoute: ProfilePasswordRoute,
  ProfilePaymentRoute: ProfilePaymentRoute,
  ProfileWishlistRoute: ProfileWishlistRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  KidsRoute: KidsRoute,
  LoginRoute: LoginRoute,
  MenRoute: MenRoute,
  NewArrivalsRoute: NewArrivalsRoute,
  ProfileRoute: ProfileRouteWithChildren,
  SignupRoute: SignupRoute,
  SnapshotRoute: SnapshotRoute,
  WishlistRoute: WishlistRoute,
  WomenRoute: WomenRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
